export {default as Costomer} from './Costomer'
export {default as Dashbord} from './Dashbord'
export {default as Inventory} from './Inventory'
export {default as Quicksale} from './Quicksale'
export {default as Report} from './Report'
export {default as Setting} from './Setting'
export {default as Login} from './Auth/Login'
export {default as Resetpassword} from './Auth/Resetpassword'
export {default as Appoitment} from './Appoitment'
export {default as Campigns} from './Campigns'
export {default as Ticket} from './Ticket'
export {default as Feedback} from './Feedback'

export {default as CostomerProfile} from './costomer/costomerProfile'
// export {default as ServiceManager} from './Setting/'
