export {default as Costomer} from './Costomer'
export {default as Dashbord} from './Dashbord'
export {default as Inventory} from './Inventory'
export {default as Quicksale} from './Quicksale'
export {default as Report} from './Report'
export {default as Setting} from './Setting'
export {default as Login} from './Auth/Login'
export {default as Resetpassword} from './Auth/Resetpassword'
export {default as Appoitment} from './Appoitment'
export {default as Campigns} from './Campigns'


export {default as SericeManager} from './Setting/SericeManager'
export {default as StaffManager} from './Setting/StaffManager'
export {default as StoreManager} from './Setting/StoreManager'
export {default as UserManger} from './Setting/UserManger'
export {default as Invoicemanager} from './Setting/invoicemanager'
export {default as productManager} from './Setting/productManager'

export {default as CostomerProfile} from './costomer/costomerProfile'
export {default as StuffProfile} from './Setting/StaffManager/stuffProfile'
// export {default as ServiceManager} from './Setting/'
